### ISSUE TITLE
Create a dev environment

### ISSUE THREAD

**Issue by katydid98** [NYU-DevOps-S18-Recommendations/recommendations#11]
**As a** Developer
**I need** a dev environment to quickly provision complex configurations and to automate the creation of a VM set-up  
**So that** all members of the team share the same development environment.  

**Assumptions:** 
* Our dev environment will be created via a Vagrantfile which will set-up the same environment for all members.

**Acceptance Criteria:**
```
Given each member has the latest Vagrantfile downloaded
When a member issues Vagrant up && Vagrant ssh command
Then a VM environment will have been created according to configurations defined 
in the Vagrantfile.
```

**Comment by katydid98** [comment]
@gau820827 @annelai @jaewhyun - added this for practice.  Can keep or delete.

**Comment by jaewhyun** [comment]
Since our story should talk about the functionality we need, should we change the issue name to:
"I need to automate the creation of a VM set-up"?

**Comment by katydid98** [comment]
Good question.  Let's add this to topic of Issue Naming for professor tomorrow.

**Comment by gau820827** [comment]
Looks good to me. The question @jaewhyun mentioned is a good one but I would vote for the origin one for now since the thing we're going to do for this story is to create a Vagrantfile and we will track the issue (the real to-do thing) on our boards.

**Comment by katydid98** [comment]
Sounds good to me! Thanks for checking it out!

**Comment by gau820827** [comment]
It's just my thought - this issue is more like a tool set-up process than developing a new feature, thus the most important component is to create the needed Vagrant file (Just as your title). In the slide, the example user story is titled "Make the hit counter......" which directly indicates that we need to make that change.
For "Make the creation of a VM set-up automatical" is also reasonable, but it's equivalent to set up a Vagrant file. So the latter sounds more intuitive to me.

Not 95% sure if that fits the purpose of a story. We could figure this out with professor tmr.

**Comment by katydid98** [comment]
@gau820827 Agree, the latter does sound more intuitive, let's see what's considered acceptable tomorrow!
